import { ImageResponse } from "next/og";
import { supabaseAdmin } from "@/lib/supabase/admin";

export const runtime = "nodejs";

/**
 * On-demand PNG renderer for one carousel slide. The tool that creates
 * the carousel uploads a JSON manifest to Supabase Storage; this route
 * fetches the manifest by ID, picks slide [idx], and renders it as a PNG
 * via Next.js ImageResponse (Satori under the hood).
 *
 * URL shape: /api/carousel/{manifestId}/slide/{idx}.png
 *   - manifestId: UUID-ish token generated by the tool (matches storage filename)
 *   - idx: zero-based slide index
 *
 * The response is a real PNG binary with long-lived cache headers so
 * teammates who open the URL get fast reads. Slides are cheap to re-render
 * if cache evicts.
 */

type Manifest = {
  title: string;
  palette: "indigo" | "emerald" | "amber" | "rose" | "slate";
  aspect_ratio: "1:1" | "4:5" | "9:16";
  slides: {
    headline: string;
    body: string;
    cta?: string | null;
  }[];
};

const PALETTES: Record<
  Manifest["palette"],
  { from: string; to: string; text: string }
> = {
  indigo: { from: "#4f46e5", to: "#06b6d4", text: "#ffffff" },
  emerald: { from: "#059669", to: "#10b981", text: "#ffffff" },
  amber: { from: "#f59e0b", to: "#ef4444", text: "#ffffff" },
  rose: { from: "#e11d48", to: "#ec4899", text: "#ffffff" },
  slate: { from: "#1e293b", to: "#475569", text: "#ffffff" },
};

const DIMS: Record<Manifest["aspect_ratio"], { w: number; h: number }> = {
  "1:1": { w: 1080, h: 1080 },
  "4:5": { w: 1080, h: 1350 },
  "9:16": { w: 1080, h: 1920 },
};

const BUCKET = "sigap-images";

async function loadManifest(id: string): Promise<Manifest | null> {
  const sb = supabaseAdmin();
  const { data } = await sb.storage
    .from(BUCKET)
    .download(`carousel-manifests/${id}.json`);
  if (!data) return null;
  try {
    const text = await data.text();
    return JSON.parse(text) as Manifest;
  } catch {
    return null;
  }
}

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ id: string; idx: string }> },
) {
  const { id, idx } = await params;
  // Trim any extension (e.g., "0.png" → "0")
  const idxClean = idx.replace(/\.png$/i, "");
  const slideIdx = Number.parseInt(idxClean, 10);
  if (!Number.isFinite(slideIdx) || slideIdx < 0) {
    return new Response("Invalid slide index", { status: 400 });
  }

  const manifest = await loadManifest(id);
  if (!manifest) {
    return new Response("Carousel manifest not found", { status: 404 });
  }
  const slide = manifest.slides[slideIdx];
  if (!slide) {
    return new Response("Slide index out of range", { status: 404 });
  }

  const palette = PALETTES[manifest.palette];
  const dims = DIMS[manifest.aspect_ratio];
  const angle = 135 + slideIdx * 15;

  // Scale typography based on aspect height so 4:5 and 9:16 feel right
  const baseScale = dims.h / 1080;
  const headlineSize = Math.round(72 * baseScale);
  const bodySize = Math.round(34 * baseScale);
  const ctaSize = Math.round(28 * baseScale);
  const meta = Math.round(24 * baseScale);
  const padding = Math.round(80 * baseScale);

  return new ImageResponse(
    (
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          width: dims.w,
          height: dims.h,
          padding,
          background: `linear-gradient(${angle}deg, ${palette.from}, ${palette.to})`,
          color: palette.text,
          fontFamily: "Inter, system-ui, sans-serif",
          position: "relative",
        }}
      >
        {/* Slide number + brand dot */}
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            fontSize: meta,
            fontWeight: 600,
            opacity: 0.7,
            letterSpacing: "0.1em",
          }}
        >
          <span>{String(slideIdx + 1).padStart(2, "0")} / {String(manifest.slides.length).padStart(2, "0")}</span>
          <span style={{ fontSize: meta }}>{manifest.title.slice(0, 40)}</span>
        </div>

        {/* Headline + body (center fill) */}
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            flexGrow: 1,
            justifyContent: "center",
            gap: Math.round(32 * baseScale),
          }}
        >
          <div
            style={{
              fontSize: headlineSize,
              fontWeight: 900,
              lineHeight: 1.1,
              letterSpacing: "-0.02em",
              display: "flex",
            }}
          >
            {slide.headline}
          </div>
          <div
            style={{
              fontSize: bodySize,
              fontWeight: 500,
              lineHeight: 1.4,
              opacity: 0.92,
              display: "flex",
            }}
          >
            {slide.body}
          </div>
        </div>

        {/* CTA bottom */}
        {slide.cta ? (
          <div
            style={{
              fontSize: ctaSize,
              fontWeight: 700,
              opacity: 0.78,
              letterSpacing: "0.08em",
              textTransform: "uppercase",
              display: "flex",
            }}
          >
            {slide.cta}
          </div>
        ) : (
          <div style={{ height: ctaSize, display: "flex" }} />
        )}
      </div>
    ),
    {
      width: dims.w,
      height: dims.h,
      headers: {
        "Cache-Control": "public, max-age=31536000, immutable",
      },
    },
  );
}
