import Link from "next/link";
import { signIn } from "@/auth";
import { auth } from "@/auth";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { InstallAcceptButton } from "@/components/install-accept-button";

type Props = {
  params: Promise<{ token: string }>;
};

/**
 * Public share-via-link landing. Visitor arrives via a link generated by
 * /api/team/skills/<id>/share-link and sees: which AI employee is being
 * shared, who shared it, and what happens on accept.
 *
 * Behavior:
 *   - Unauthenticated → "Sign in with Google to activate" CTA (wraps
 *     signIn server action and preserves the install URL as callback)
 *   - Authenticated → "Activate in your workspace" button (client) →
 *     POSTs /api/install/<token>/accept → redirects to /agents/<slug>
 */
export default async function InstallPage({ params }: Props) {
  const { token } = await params;
  const session = await auth();
  const loggedIn = Boolean(session?.user);

  const sb = supabaseAdmin();
  const { data: tmpl } = await sb
    .from("org_agent_templates")
    .select(
      "id, org_id, name, emoji, description, enabled_tools, published_by",
    )
    .eq("share_token", token)
    .maybeSingle();

  if (!tmpl) {
    return (
      <main className="mx-auto max-w-lg px-6 py-24 text-center">
        <p className="text-5xl">🔗</p>
        <h1 className="mt-4 text-2xl font-bold text-slate-900">
          This link isn&apos;t valid
        </h1>
        <p className="mt-2 text-sm text-slate-600">
          The share link may have been revoked or the employee removed.
        </p>
        <Link
          href="/"
          className="mt-6 inline-block rounded-md border border-slate-200 bg-white px-4 py-2 text-sm hover:bg-slate-50"
        >
          Go to Cowork →
        </Link>
      </main>
    );
  }

  // Shared-by name
  let sharedByName: string | null = null;
  if (tmpl.published_by) {
    const { data: u } = await sb
      .from("users")
      .select("name, email")
      .eq("id", tmpl.published_by)
      .maybeSingle();
    sharedByName =
      (u?.name as string | null) ?? (u?.email as string | null) ?? null;
  }

  // Org name
  const { data: org } = await sb
    .from("organizations")
    .select("name")
    .eq("id", tmpl.org_id)
    .maybeSingle();
  const orgName = (org?.name as string) ?? "A team";

  async function signInAndInstall() {
    "use server";
    await signIn("google", { redirectTo: `/install/${token}` });
  }

  return (
    <main className="mx-auto max-w-2xl px-6 py-16">
      <nav className="mb-12 flex items-center gap-2 text-sm text-slate-500">
        <Link href="/" className="flex items-center gap-2">
          <span className="inline-block h-6 w-6 rounded-md bg-gradient-to-br from-indigo-600 to-cyan-400" />
          <span className="font-semibold text-slate-900">Cowork</span>
        </Link>
      </nav>

      <div className="rounded-2xl border border-slate-200 bg-white p-8 shadow-sm">
        <p className="text-xs font-semibold uppercase tracking-wider text-indigo-600">
          You&apos;ve been invited
        </p>
        <h1 className="mt-3 text-3xl font-bold text-slate-900">
          {sharedByName ? (
            <>
              {sharedByName} from {orgName}
              <br />
              wants to share an AI employee with you
            </>
          ) : (
            <>{orgName} wants to share an AI employee with you</>
          )}
        </h1>

        <div className="mt-8 rounded-xl border border-slate-200 bg-slate-50 p-6">
          <div className="flex items-start gap-4">
            <span className="text-4xl">{tmpl.emoji ?? "🤖"}</span>
            <div className="min-w-0 flex-1">
              <h2 className="text-xl font-semibold text-slate-900">
                {tmpl.name}
              </h2>
              {tmpl.description && (
                <p className="mt-1 text-sm text-slate-600">
                  {tmpl.description}
                </p>
              )}
              <div className="mt-3 flex flex-wrap gap-1.5">
                {((tmpl.enabled_tools as string[] | null) ?? [])
                  .slice(0, 8)
                  .map((tool) => (
                    <span
                      key={tool}
                      className="rounded-full bg-indigo-50 px-2 py-0.5 font-mono text-[10px] text-indigo-700"
                    >
                      {tool}
                    </span>
                  ))}
              </div>
            </div>
          </div>
        </div>

        <div className="mt-8">
          {loggedIn ? (
            <InstallAcceptButton token={token} />
          ) : (
            <form action={signInAndInstall}>
              <button
                type="submit"
                className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-6 py-3 text-sm font-medium text-white hover:bg-indigo-500"
              >
                <svg width="18" height="18" viewBox="0 0 24 24">
                  <path
                    fill="#fff"
                    d="M21.8 10.2h-9.8v3.9h5.6c-.2 1.5-1.6 4.4-5.6 4.4a6.5 6.5 0 1 1 0-13c2 0 3.4.9 4.1 1.6l2.8-2.7C17.1 2.8 14.8 1.9 12 1.9A10 10 0 1 0 22 12a9.6 9.6 0 0 0-.2-1.8z"
                  />
                </svg>
                Sign in with Google to activate →
              </button>
            </form>
          )}
          <p className="mt-3 text-xs text-slate-500">
            Activating will join you to {orgName} and add {tmpl.name} to your
            personal workspace. You can chat with them immediately.
          </p>
        </div>
      </div>
    </main>
  );
}
